# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc ""
  homepage "https://github.com/yodamad/heimdall"
  version "0.6.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yodamad/heimdall/releases/download/v0.6.0/heimdall_Darwin_x86_64.tar.gz"
      sha256 "8ccaf237831a82f7e164a3afb88b4418d60652891a00739e0b0e992fec8f866e"

      def install
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yodamad/heimdall/releases/download/v0.6.0/heimdall_Darwin_arm64.tar.gz"
      sha256 "022dc5a807966ed12372f5231ddeff7f56d201d1a88da5b9a2c2b6535c11cead"

      def install
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yodamad/heimdall/releases/download/v0.6.0/heimdall_Linux_x86_64.tar.gz"
      sha256 "99e05e5b3f6b25840d54ca0a00814538a61e3f32c0b1cb1c407fbfaa37ba2491"
      def install
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yodamad/heimdall/releases/download/v0.6.0/heimdall_Linux_arm64.tar.gz"
      sha256 "a14b3440bd28637d7db50ffdc2f1ce8ef8857722e8a02bb3e110f5a996bbf4de"
      def install
        bin.install "heimdall"
      end
    end
  end
end
