# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc ""
  homepage "https://github.com/yodamad/heimdall"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/yodamad/heimdall/releases/download/0.1.0/heimdall_Darwin_x86_64.tar.gz"
      sha256 "c3e9987ec0d44162a729f53f3111b9cb5c9cb2357c96de3c126f5478a3cead6a"

      def install
        bin.install "heimdall"
      end
    end
    on_arm do
      url "https://github.com/yodamad/heimdall/releases/download/0.1.0/heimdall_Darwin_arm64.tar.gz"
      sha256 "25d477cc707e85277e2df5347bec01fe714a3ebd39aa5f1cf8edcadc516a5005"

      def install
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yodamad/heimdall/releases/download/0.1.0/heimdall_Linux_x86_64.tar.gz"
        sha256 "e6e4c09752b547faffe59dbb5d0bd2056d4684cfbe00ba8446cbd830ce05866d"

        def install
          bin.install "heimdall"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yodamad/heimdall/releases/download/0.1.0/heimdall_Linux_arm64.tar.gz"
        sha256 "a2d22701a4338e887990db5bbe9cb4835da39417ed03a156b679fed6d75f4463"

        def install
          bin.install "heimdall"
        end
      end
    end
  end
end
