# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slidesk < Formula
  desc ""
  homepage "https://github.com/yodamad/slidesk"
  version "0.4.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yodamad/heimdall/releases/download/0.4.0/heimdall_Darwin_x86_64.tar.gz"
      sha256 "9024fcdb1559f900cb1cc505c1534e82a092d2530ce9486ff7b39990543b3af6"

      def install
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yodamad/heimdall/releases/download/0.4.0/heimdall_Darwin_arm64.tar.gz"
      sha256 "91219d0d10c6fef3b95712a47020d5724adbf4069232ede9abb79c366ac7ccf2"

      def install
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yodamad/heimdall/releases/download/0.4.0/heimdall_Linux_x86_64.tar.gz"
        sha256 "606a5c2a1b9e0a9e51f2cc933b76859e90253824ffb2679db58edd119fcb8874"

        def install
          bin.install "heimdall"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yodamad/heimdall/releases/download/0.4.0/heimdall_Linux_arm64.tar.gz"
        sha256 "0be9efbce1e42653ae576a5a3e2618cbf58619c6abd074d74f3fec3e9bdbd897"

        def install
          bin.install "heimdall"
        end
      end
    end
  end
end
