# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraptor" do
  name "migraptor"
  desc ""
  homepage "https://github.com/yodamad/migraptor"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraptor"

  on_macos do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_x86_64.tar.gz"
      sha256 "8b33299866fa4500abb426b68b6999e2e2b8df0c554d14a31bb3fe30bc7c190e"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_arm64.tar.gz"
      sha256 "7e24306140183c1f26f1d1938ee2867a314c6cf2332906cd36d361679cc91165"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_x86_64.tar.gz"
      sha256 "ec5a8cc2665756474a6eb157fa7396f95d1fdbc4f7f8cb58b9de6dbe7f3e9e70"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_arm64.tar.gz"
      sha256 "cf912f8ed0742fb0471990162b7393cc6f64d6f6a6f402f5853c5ca2de6528aa"
    end
  end

  # No zap stanza required
end
