# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraptor" do
  name "migraptor"
  desc ""
  homepage "https://github.com/yodamad/migraptor"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraptor"

  on_macos do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_x86_64.tar.gz"
      sha256 "7ea9fec29f0d6db0c676a7829c6dd20c953345dcfbac2751c3f78413b3e01265"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_arm64.tar.gz"
      sha256 "d57636ba26415e0790d6a4ca20bcbf4ea435e6531e3d8b8f46e290d4eda11c9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_x86_64.tar.gz"
      sha256 "c69a2808e304f2cace9c1f713c2c9db4366ef8e213b1f94c8511a77a767c3f75"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_arm64.tar.gz"
      sha256 "50a884b591ae79f0e252bbf010ec7e4ac07527ace3ce8b7db365b1e48cc06bc3"
    end
  end

  # No zap stanza required
end
