# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraptor" do
  name "migraptor"
  desc ""
  homepage "https://github.com/yodamad/migraptor"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraptor"

  on_macos do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_x86_64.tar.gz"
      sha256 "088cde51cdeef5831320eed041f9601a5cfa2b3d55428e6f7ca06510d36a01bc"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Darwin_arm64.tar.gz"
      sha256 "83121bc799a9ceef07d6b33a463ffe1efc669157b35835ca78db56e55e380d5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_x86_64.tar.gz"
      sha256 "f8c48bbcf2bee91905128483203c68c39db8ba2243f432dbece63ff501881da5"
    end
    on_arm do
      url "https://github.com/yodamad/migraptor/releases/download/#{version}/migraptor_Linux_arm64.tar.gz"
      sha256 "0d06e67f7dc400693d04961db3af42d81fa7956472d68a2ad1d5572585df7ca2"
    end
  end

  # No zap stanza required
end
